--- 

- name: Install and configure NGINX using yum
  yum:
    name:
      - nginx
    state: present

- name: Deploy nginx.conf from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf_result

- name: Restart nginx if config was copied/changed
  service: 
    name: nginx
    state: restarted
  when: nginx_conf_result.changed
  become: true

- name: Turn on the NGINX service
  service:
    name: nginx
    state: started
    enabled: yes
  become: true