---

- name: Upload website files
  copy:
    src: /home/vin/unix-practice/ansible/configProject1/website.tar.gz
    dest: /tmp/website.tar.gz

- name: Extract website
  unarchive:
    src: /tmp/website.tar.gz
    dest: /var/www/html
    remote_src: yes