---
- hosts: all
  become: true
  tasks:
    - name: install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: yes

    - name: start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes